### ISSUE TITLE
Is this same code as was previously on the wiki page?

### ISSUE THREAD

**Issue by smazurchuk** [gkaguirrelab/t1i1Seqgen#2]
Hi All,

Thanks for making this code available. I'm not sure if you guys are aware that many (most?) of the links on the wiki page for t1I1 sequences no longer work? Specifically those at: https://cfn.upenn.edu/aguirre/wiki/doku.php?id=public:t1i1_sequences

My question is if the code in this repository is the same as what was originally referenced at this link:

![image](https://user-images.githubusercontent.com/29523859/151583536-fea39b04-9b92-4e0f-9757-5e7c5a966d73.png)

If it is, should the link on the wiki be re-directed here?

**Comment by gkaguirre** [comment]
Yes, same code as was on the wiki.

Thanks for alerting me to the outdated wiki links! We will start doing some updating…

Geoff


> On Jan 28, 2022, at 11:23 AM, Stephen Mazurchuk ***@***.***> wrote:
> 
> 
> Hi All,
> 
> Thanks for making this code available. I'm not sure if you guys are aware that many (most?) of the links on the wiki page for t1l1 sequences no longer work? Specifically those at: https://cfn.upenn.edu/aguirre/wiki/doku.php?id=public:t1i1_sequences
> 
> My question is if the code in this repository is the same as what was originally referenced at this link:
> 
> 
> If it is, should the link on the wiki be re-directed here?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.
> 

--

Geoffrey Karl Aguirre, M.D., Ph.D.
http://gkaguirre.com
Professor of Neurology
University of Pennsylvania
Philadelphia, PA

**Comment by smazurchuk** [comment]
Great! Thanks!
